// J1939 SPN (Suspect Parameter Number) and FMI (Failure Mode Identifier) lookup
// Covers common heavy-duty truck SPNs seen on 2013+ Mack/Volvo

export const FMI_DESCRIPTIONS: Record<number, string> = {
  0: "Data valid but above normal range",
  1: "Data valid but below normal range",
  2: "Data erratic, intermittent, or incorrect",
  3: "Voltage above normal or shorted high",
  4: "Voltage below normal or shorted low",
  5: "Current below normal or open circuit",
  6: "Current above normal or grounded",
  7: "Mechanical system not responding properly",
  8: "Abnormal frequency, pulse width, or period",
  9: "Abnormal update rate",
  10: "Abnormal rate of change",
  11: "Root cause not known",
  12: "Bad intelligent device or component",
  13: "Out of calibration",
  14: "Special instructions",
  15: "Data valid but above normal — least severe",
  16: "Data valid but above normal — moderately severe",
  17: "Data valid but below normal — least severe",
  18: "Data valid but below normal — moderately severe",
  19: "Received network data in error",
  20: "Data drifted high",
  21: "Data drifted low",
  31: "Condition exists",
};

export interface SPNInfo {
  name: string;
  description: string;
  fix: string;
  severity: "info" | "warning" | "critical";
}

export const SPN_LOOKUP: Record<number, SPNInfo> = {
  // Engine
  27: { name: "EGR Valve Position", description: "Exhaust Gas Recirculation valve position sensor", fix: "Check EGR valve for carbon buildup, clean or replace", severity: "warning" },
  51: { name: "Throttle Position", description: "Throttle position sensor circuit", fix: "Check throttle position sensor wiring, replace sensor if faulty", severity: "warning" },
  84: { name: "Vehicle Speed", description: "Wheel-based vehicle speed sensor", fix: "Check speed sensor and wiring at transmission", severity: "warning" },
  91: { name: "Accelerator Pedal Position", description: "Accelerator pedal or lever position sensor", fix: "Check pedal sensor connector, replace sensor", severity: "warning" },
  94: { name: "Fuel Delivery Pressure", description: "Fuel pressure at the injection pump", fix: "Check fuel filter, fuel lines, lift pump", severity: "warning" },
  97: { name: "Water in Fuel", description: "Water detected in fuel system", fix: "Drain water separator, replace fuel filter", severity: "warning" },
  100: { name: "Engine Oil Pressure", description: "Engine oil pressure sensor or actual pressure", fix: "Check oil level, oil pressure sensor, oil pump", severity: "critical" },
  102: { name: "Boost Pressure", description: "Turbocharger boost pressure", fix: "Check turbo, intercooler hoses, boost pressure sensor", severity: "warning" },
  105: { name: "Intake Manifold Temperature", description: "Intake manifold air temperature", fix: "Check intake temp sensor, intercooler", severity: "info" },
  107: { name: "Air Filter Restriction", description: "Air filter differential pressure", fix: "Replace air filter element", severity: "info" },
  108: { name: "Barometric Pressure", description: "Barometric pressure sensor", fix: "Check sensor, usually altitude-related", severity: "info" },
  110: { name: "Engine Coolant Temperature", description: "Engine coolant temperature sensor", fix: "Check coolant level, thermostat, temp sensor", severity: "critical" },
  111: { name: "Coolant Level", description: "Engine coolant level sensor", fix: "Check coolant level, top up, check for leaks", severity: "critical" },
  157: { name: "Injector Timing Rail Pressure", description: "Common rail fuel pressure", fix: "Check high-pressure fuel pump, rail pressure sensor, injectors", severity: "critical" },
  158: { name: "Battery Voltage", description: "Battery/charging system voltage", fix: "Check alternator, battery connections, battery condition", severity: "warning" },
  164: { name: "Injection Control Pressure", description: "HEUI injection control pressure", fix: "Check IPR valve, high-pressure oil pump", severity: "critical" },
  168: { name: "Battery Potential", description: "Electrical system battery voltage", fix: "Check alternator output, battery cables, batteries", severity: "warning" },
  171: { name: "Ambient Air Temperature", description: "Outside air temperature sensor", fix: "Check ambient temp sensor", severity: "info" },
  174: { name: "Fuel Temperature", description: "Fuel temperature sensor", fix: "Check fuel temp sensor, fuel return line", severity: "info" },
  175: { name: "Engine Oil Temperature", description: "Engine oil temperature sensor", fix: "Check oil temp sensor, oil cooler", severity: "warning" },
  190: { name: "Engine Speed", description: "Engine RPM sensor (crankshaft)", fix: "Check crankshaft position sensor and wiring", severity: "critical" },

  // Aftertreatment / Emissions (very common on 2013+ trucks)
  520: { name: "Actual Engine Torque", description: "Actual engine percent torque", fix: "Check engine sensors, may be derate condition", severity: "warning" },
  523: { name: "Transmission Current Gear", description: "Current transmission gear", fix: "Check transmission controller, gear sensor", severity: "warning" },
  524: { name: "Transmission Selected Gear", description: "Selected transmission gear", fix: "Check gear selector, transmission controller", severity: "warning" },
  597: { name: "Brake Switch", description: "Brake pedal switch", fix: "Check brake light switch, wiring", severity: "warning" },
  598: { name: "Clutch Switch", description: "Clutch pedal switch", fix: "Check clutch switch, wiring", severity: "info" },
  611: { name: "Crankcase Pressure", description: "Engine crankcase pressure", fix: "Check crankcase breather, worn rings possible", severity: "warning" },
  627: { name: "Compressor Discharge Pressure", description: "A/C compressor discharge pressure", fix: "Check A/C system pressure, refrigerant level", severity: "info" },
  629: { name: "ECU Internal", description: "Engine Control Unit internal fault", fix: "Try key cycle, reflash ECU if persistent", severity: "critical" },
  630: { name: "ECU Power Supply", description: "ECU power supply voltage", fix: "Check ECU power/ground connections", severity: "critical" },
  651: { name: "Injector Cylinder 1", description: "Fuel injector #1 circuit", fix: "Check injector wiring, replace injector", severity: "critical" },
  652: { name: "Injector Cylinder 2", description: "Fuel injector #2 circuit", fix: "Check injector wiring, replace injector", severity: "critical" },
  653: { name: "Injector Cylinder 3", description: "Fuel injector #3 circuit", fix: "Check injector wiring, replace injector", severity: "critical" },
  654: { name: "Injector Cylinder 4", description: "Fuel injector #4 circuit", fix: "Check injector wiring, replace injector", severity: "critical" },
  655: { name: "Injector Cylinder 5", description: "Fuel injector #5 circuit", fix: "Check injector wiring, replace injector", severity: "critical" },
  656: { name: "Injector Cylinder 6", description: "Fuel injector #6 circuit", fix: "Check injector wiring, replace injector", severity: "critical" },
  723: { name: "Engine Brake Actuator", description: "Engine brake / jake brake actuator", fix: "Check engine brake solenoid and wiring", severity: "warning" },
  899: { name: "Engine Torque Mode", description: "Engine torque limitation active", fix: "Check for other active codes causing derate", severity: "warning" },

  // DPF / SCR / DEF (most common modern truck codes)
  1569: { name: "DPF Outlet Temperature", description: "Diesel Particulate Filter outlet temp sensor", fix: "Check DPF outlet temp sensor, do regen if needed", severity: "warning" },
  1761: { name: "DPF Differential Pressure", description: "DPF soot load differential pressure", fix: "Perform forced regen, clean/replace DPF if high soot", severity: "warning" },
  2631: { name: "DPF Active Regen", description: "DPF active regeneration status", fix: "Allow regen to complete, do not shut off engine during regen", severity: "info" },
  2659: { name: "DPF Status", description: "Diesel Particulate Filter overall status", fix: "Check DPF soot load, perform regen or clean DPF", severity: "warning" },
  3216: { name: "AFT SCR Conversion", description: "Aftertreatment SCR catalyst conversion efficiency", fix: "Check DEF quality, SCR catalyst, NOx sensors", severity: "warning" },
  3226: { name: "AFT DEF Tank Level", description: "Aftertreatment Diesel Exhaust Fluid tank level", fix: "Top up DEF fluid. Check DEF level sensor if full but showing low", severity: "warning" },
  3230: { name: "AFT SCR Intake NOx", description: "SCR intake NOx sensor reading", fix: "Check NOx sensor, DEF dosing, SCR catalyst", severity: "warning" },
  3242: { name: "AFT DEF Quality", description: "DEF (urea) quality/concentration", fix: "Drain and replace DEF with fresh fluid, check DEF quality sensor", severity: "warning" },
  3246: { name: "AFT DEF Dosing", description: "DEF dosing valve or pump", fix: "Check DEF pump, dosing valve, DEF lines for crystallization", severity: "warning" },
  3251: { name: "AFT SCR Outlet NOx", description: "SCR outlet NOx sensor reading", fix: "Check outlet NOx sensor, SCR catalyst efficiency", severity: "warning" },
  3362: { name: "AFT DPF Inlet Temperature", description: "DPF inlet exhaust temperature", fix: "Check DPF inlet temp sensor and wiring", severity: "warning" },
  3364: { name: "AFT DOC Inlet Temperature", description: "Diesel Oxidation Catalyst inlet temp", fix: "Check DOC inlet temp sensor", severity: "warning" },
  3556: { name: "AFT DEF Tank Temperature", description: "DEF fluid temperature in tank", fix: "Check DEF tank heater in cold weather, temp sensor", severity: "info" },
  3563: { name: "AFT 7th Injector", description: "Aftertreatment hydrocarbon injector (DPF regen)", fix: "Check 7th injector for fuel supply and operation", severity: "warning" },
  3609: { name: "AFT DEF Line Heater", description: "DEF supply line heater circuit", fix: "Check DEF line heater relay and wiring, common in cold weather", severity: "info" },
  3610: { name: "AFT DEF Return Line Heater", description: "DEF return line heater", fix: "Check DEF return heater relay and wiring", severity: "info" },
  3719: { name: "AFT DEF Pump Pressure", description: "DEF pump/dosing system pressure", fix: "Check DEF pump, filter, lines for blockage or crystallization", severity: "warning" },

  // Transmission / Drivetrain
  4078: { name: "Trans Oil Life", description: "Transmission fluid life remaining", fix: "Schedule transmission fluid change", severity: "info" },

  // Body / Cab
  5018: { name: "High Beam", description: "High beam headlight circuit", fix: "Check headlight bulb, relay, wiring", severity: "info" },
  5246: { name: "AFT System Status", description: "Overall aftertreatment system status/derate warning", fix: "Check DEF level and quality, clear codes after fix, monitor", severity: "warning" },

  // Common Mack/Volvo specific
  3031: { name: "EGR Mass Flow", description: "EGR system mass flow rate", fix: "Clean EGR valve and cooler, check EGR actuator", severity: "warning" },
  3936: { name: "AFT DPF Soot Load", description: "DPF soot load percentage", fix: "Perform forced regen, replace DPF if soot won't burn off", severity: "warning" },
  4094: { name: "NOx Level Exceeded", description: "Tailpipe NOx emissions exceed limit", fix: "Check DEF system, SCR catalyst, may trigger derate", severity: "critical" },
  4364: { name: "Coolant Flow", description: "Engine coolant flow rate", fix: "Check water pump, thermostat, coolant hoses", severity: "warning" },
  5298: { name: "Idle Shutdown Timer", description: "Engine idle shutdown timer active", fix: "Normal operation — engine will shut down after idle timer", severity: "info" },

  // ── Additional SPNs (200 total) ──
  38: { name: "Ext Cab Air Temp", description: "External air temperature for cab climate control", fix: "Check ambient temp sensor behind bumper or mirror", severity: "info" },
  74: { name: "Max Vehicle Speed", description: "Maximum speed limit programmed in ECM", fix: "Adjust via ECM parameter programming with PTT", severity: "info" },
  79: { name: "Road Surface Condition", description: "Detected road surface condition (dry, wet, icy)", fix: "Informational from stability control system", severity: "info" },
  80: { name: "Washer Fluid Level", description: "Windshield washer fluid reservoir level", fix: "Refill washer fluid, check level sensor", severity: "info" },
  86: { name: "Cruise Set Speed", description: "Cruise control speed set point", fix: "Check cruise switches, brake/clutch switches, VSS", severity: "info" },
  92: { name: "Engine Load", description: "Percent load at current speed", fix: "If pegged at 100%, investigate turbo, fueling, or excessive load", severity: "info" },
  96: { name: "Fuel Level", description: "Fuel level in primary tank as percentage", fix: "Check fuel level sender unit, wiring, instrument cluster", severity: "info" },
  98: { name: "Engine Oil Level", description: "Electronic oil level sensor reading", fix: "Check dipstick, inspect oil level sensor in oil pan", severity: "warning" },
  103: { name: "Turbo Speed (Alt)", description: "Alternate turbocharger speed parameter", fix: "Check turbo speed sensor and wiring", severity: "warning" },
  106: { name: "Intake Manifold Pressure", description: "Absolute pressure in intake manifold (MAP)", fix: "Check MAP sensor, boost leaks, turbo connections", severity: "warning" },
  109: { name: "Coolant Pressure", description: "Engine cooling system pressure", fix: "Check radiator cap, head gasket, water pump", severity: "warning" },
  114: { name: "Net Battery Current", description: "Net electrical current into/out of battery", fix: "Check alternator, belt, electrical loads", severity: "warning" },
  132: { name: "Mass Airflow", description: "Mass of air flowing into engine intake", fix: "Check MAF sensor, often calculated from MAP and IAT on Volvo/Mack", severity: "warning" },
  161: { name: "Trans Input Shaft Speed", description: "Transmission input shaft rotational speed", fix: "Check input shaft speed sensor and wiring", severity: "warning" },
  166: { name: "Engine Rated Power", description: "Maximum rated engine power in ECM calibration", fix: "Verify correct ECM calibration via PTT", severity: "info" },
  167: { name: "Alternator Speed", description: "Rotational speed of alternator", fix: "Check belt slip or incorrect pulley ratio", severity: "info" },
  170: { name: "Cab Interior Temp", description: "Interior cabin temperature for climate control", fix: "Check interior temp sensor and aspirator fan", severity: "info" },
  172: { name: "Intake Air Temp (Pre-CAC)", description: "Air temp at turbo compressor inlet", fix: "Check sensor, ensure intake not drawing hot underhood air", severity: "info" },
  173: { name: "Exhaust Temp (Pre-Turbo)", description: "Exhaust gas temperature at manifold", fix: "Monitor for over-temp, check injection timing and turbo", severity: "warning" },
  183: { name: "Fuel Rate", description: "Current fuel consumption rate", fix: "Abnormally high suggests injector issues or turbo problems", severity: "info" },
  188: { name: "Engine Turbo Speed (Alt)", description: "Alternative turbocharger speed parameter", fix: "Check turbo speed sensor, overspeed = boost issue", severity: "warning" },
  191: { name: "Trans Output Shaft Speed", description: "Transmission output shaft speed", fix: "Check output shaft speed sensor, tone ring, wiring", severity: "warning" },
  235: { name: "Total Engine Hours", description: "Accumulated engine operation time", fix: "Informational for maintenance scheduling", severity: "info" },
  237: { name: "Vehicle Miles", description: "Total accumulated distance traveled", fix: "Verify against odometer if discrepancy", severity: "info" },
  241: { name: "Tire Pressure - LF", description: "Left front tire inflation pressure (TPMS)", fix: "Inflate to spec, check for puncture, replace TPMS sensor", severity: "warning" },
  242: { name: "Tire Pressure - RF", description: "Right front tire inflation pressure (TPMS)", fix: "Inflate to spec, inspect tire for damage", severity: "warning" },
  243: { name: "Tire Pressure - LR Outer", description: "Left rear outer tire pressure (TPMS)", fix: "Inflate to spec, check for bead or puncture leaks", severity: "warning" },
  244: { name: "Tire Pressure - RR Outer", description: "Right rear outer tire pressure (TPMS)", fix: "Inflate to spec, check valve stem extender on outer dual", severity: "warning" },
  245: { name: "Tire Temp - LF", description: "Left front tire temperature (TPMS)", fix: "Hot tire = underinflation, overload, or dragging brake", severity: "warning" },
  247: { name: "Total Engine PTO Hours", description: "Accumulated PTO operation hours", fix: "Informational for PTO maintenance scheduling", severity: "info" },
  250: { name: "Total Idle Fuel", description: "Total fuel consumed during idle", fix: "High ratio indicates excessive idling, review idle shutdown settings", severity: "info" },
  411: { name: "EGR Delta Pressure", description: "Differential pressure across EGR valve", fix: "Clean EGR valve and passages, replace diff pressure sensor", severity: "warning" },
  412: { name: "EGR Temperature", description: "Recirculated exhaust gas temperature", fix: "Check EGR cooler for leaks, replace EGR temp sensor", severity: "warning" },
  441: { name: "EGR Valve Position (Cmd)", description: "Commanded EGR valve position by ECM", fix: "Compare to actual, clean or replace EGR actuator if stuck", severity: "info" },
  442: { name: "EGR Valve Position (Actual)", description: "Actual measured EGR valve position", fix: "If deviating from command: clean valve, replace actuator", severity: "warning" },
  512: { name: "Driver Demand Torque", description: "Percent torque requested via accelerator", fix: "If not tracking pedal, check pedal sensor and ECM calibration", severity: "info" },
  513: { name: "Actual Engine Torque", description: "Current engine output torque percentage", fix: "Informational for driveline coordination", severity: "info" },
  514: { name: "Nominal Friction Torque", description: "Estimated engine friction/parasitic losses", fix: "High friction may indicate bearing or oil viscosity issues", severity: "info" },
  515: { name: "Engine Demand Torque", description: "Total torque demanded by engine control", fix: "Informational, compare to actual torque", severity: "info" },
  522: { name: "Trans Oil Temp", description: "Transmission oil temperature", fix: "Check trans oil level, oil cooler, cooler lines", severity: "warning" },
  525: { name: "Trans Selected Gear", description: "Gear selected by driver or TCM", fix: "If selected != current, check shift actuator, clutch actuator", severity: "info" },
  526: { name: "Trans Gear Ratio", description: "Actual calculated gear ratio", fix: "If ratio doesn't match known gears, suspect slipping clutch", severity: "info" },
  527: { name: "Cruise Control Active", description: "Cruise control system status", fix: "Check brake switch, clutch switch, VSS signal", severity: "info" },
  558: { name: "Accel Pedal Low Idle Switch", description: "Accelerator pedal idle validation switch", fix: "Check idle switch in pedal assembly", severity: "warning" },
  560: { name: "Trans Range Selected", description: "Driver-selected range (D, N, R, L)", fix: "Check range selector switch, shift lever, wiring", severity: "warning" },
  561: { name: "ABS Active", description: "ABS actively modulating brake pressure", fix: "If unexpected: check wheel speed sensors, tone rings, air gaps", severity: "info" },
  563: { name: "ABS Off-Road Switch", description: "ABS off-road disable switch status", fix: "Verify switch position if ABS appears disabled", severity: "info" },
  571: { name: "PTO Status", description: "Power Take-Off engagement status", fix: "Check PTO switch, engagement solenoid, interlock conditions", severity: "info" },
  572: { name: "PTO Set Speed", description: "PTO governor engine speed set point", fix: "Check PTO speed sensor, ECM programming, throttle input", severity: "info" },
  573: { name: "Trans Shift Inhibit", description: "Transmission inhibiting shifts due to fault", fix: "Check for active transmission codes, speed sensors, clutch actuator", severity: "warning" },
  582: { name: "Gross Vehicle Weight", description: "Total vehicle weight from onboard scale", fix: "Calibrate onboard scale, check suspension height sensors", severity: "info" },
  583: { name: "Idle Shutdown Timer", description: "Remaining time before auto idle shutdown", fix: "Check idle shutdown programming in ECM via PTT", severity: "info" },
  584: { name: "Idle Shutdown Override", description: "Idle shutdown override status", fix: "Check override switch and wiring", severity: "info" },
  593: { name: "HVAC Blower Speed", description: "HVAC blower motor speed", fix: "Check blower motor, resistor pack, fuse, switch", severity: "info" },
  594: { name: "HVAC Mode Position", description: "HVAC air distribution mode door", fix: "Check mode door actuator motor and linkage", severity: "info" },
  595: { name: "HVAC Recirc/Fresh Position", description: "Recirculation/fresh air door position", fix: "Check recirc door actuator, causes fogging if stuck", severity: "info" },
  596: { name: "HVAC Blend Door Position", description: "Hot/cold air blend door position", fix: "Check blend door actuator, heater core flow, A/C", severity: "info" },
  625: { name: "CAN Bus Error (J1939)", description: "J1939 data link communication error", fix: "Check CAN wiring, terminating resistors (120 ohm), connectors", severity: "critical" },
  626: { name: "CAN Bus Error (J1708)", description: "Legacy J1708/J1587 data link error", fix: "Check J1708 wiring, terminating resistors", severity: "warning" },
  628: { name: "Key Switch Battery Voltage", description: "Battery voltage at ignition switch", fix: "Check ignition switch, wiring, fuse/relay panel", severity: "warning" },
  636: { name: "ECU CAN Bus Timeout", description: "Expected CAN message not received", fix: "Check which ECU is not communicating, inspect CAN wiring", severity: "warning" },
  639: { name: "J1939 Network #2 Error", description: "Secondary J1939 CAN segment fault", fix: "Check secondary CAN bus wiring and connectors", severity: "warning" },
  641: { name: "VGT Actuator Driver", description: "ECM driver circuit for VGT actuator", fix: "Check VGT actuator connector, wiring, ECM output pin", severity: "warning" },
  647: { name: "Fan Clutch Output Driver", description: "Cooling fan clutch solenoid driver", fix: "Check fan clutch solenoid, wiring, fuse", severity: "warning" },
  677: { name: "Starter Relay Driver", description: "Starter motor relay driver circuit", fix: "Check starter relay, wiring, neutral/park switch", severity: "warning" },
  702: { name: "Power Relay (Main)", description: "Main power/ECU latch relay", fix: "Check main power relay, wiring, fuse — common no-start cause", severity: "warning" },
  789: { name: "Wheel Speed - LF", description: "Left front ABS wheel speed sensor", fix: "Check sensor, tone ring, gap, wiring", severity: "warning" },
  790: { name: "Wheel Speed - RF", description: "Right front ABS wheel speed sensor", fix: "Check sensor, tone ring, connector corrosion", severity: "warning" },
  791: { name: "Wheel Speed - LR", description: "Left rear ABS wheel speed sensor", fix: "Check sensor mounting, tone ring condition", severity: "warning" },
  792: { name: "Wheel Speed - RR", description: "Right rear ABS wheel speed sensor", fix: "Check sensor, tone ring, connector", severity: "warning" },
  802: { name: "ABS Lamp Status", description: "ABS warning lamp on dashboard", fix: "Read ABS codes with Bendix ACom, check wheel speed sensors first", severity: "warning" },
  929: { name: "Engine Overspeed", description: "Engine exceeded max RPM limit", fix: "Check for runaway condition, turbo seal failure, downshift error", severity: "critical" },
  963: { name: "Door Switch - Driver", description: "Driver side door open/closed switch", fix: "Adjust or replace door jamb switch", severity: "info" },
  964: { name: "Door Switch - Passenger", description: "Passenger door open/closed switch", fix: "Check door switch, wiring in hinge area", severity: "info" },
  970: { name: "Brake Lining - LF", description: "Left front brake lining remaining", fix: "Replace brake pads/shoes, inspect drums/rotors", severity: "warning" },
  971: { name: "Brake Lining - RF", description: "Right front brake lining remaining", fix: "Replace pads/shoes, check for uneven wear", severity: "warning" },
  972: { name: "Brake Lining - LR", description: "Left rear brake lining remaining", fix: "Replace shoes, inspect slack adjuster", severity: "warning" },
  973: { name: "Brake Lining - RR", description: "Right rear brake lining remaining", fix: "Replace shoes, check for oil contamination from wheel seals", severity: "warning" },
  976: { name: "Crankcase Pressure", description: "Engine crankcase pressure (CCV sensor)", fix: "Check CCV filter, breather system, piston ring blow-by", severity: "warning" },
  1082: { name: "Engine Brake Status", description: "Compression brake (jake brake) activation", fix: "Check engine brake solenoids, dash switch, lash adjustment", severity: "info" },
  1083: { name: "Engine Brake Select", description: "Engine brake level selected by driver", fix: "Check selector switch on dash, wiring, ECM input", severity: "info" },
  1086: { name: "Brake Application Pressure", description: "Air pressure to service brake chambers", fix: "Check treadle valve, relay valves, slack adjusters, leaks", severity: "warning" },
  1087: { name: "Primary Air Tank Pressure", description: "Primary brake air tank pressure", fix: "Check for air leaks, compressor, governor, air dryer", severity: "critical" },
  1088: { name: "Secondary Air Tank Pressure", description: "Secondary brake air tank pressure", fix: "Check for leaks in secondary circuit, check valve between tanks", severity: "critical" },
  1121: { name: "Park Brake Status", description: "Parking/spring brake applied/released", fix: "Check parking brake valve, spring brake chambers, air supply", severity: "info" },
  1172: { name: "Turbo Compressor Inlet Temp", description: "Air temp entering turbo compressor", fix: "Check air filter restriction, underhood temps", severity: "info" },
  1173: { name: "Turbo Compressor Outlet Temp", description: "Compressed air temp leaving turbo", fix: "If excessive, turbo working too hard — check boost leak", severity: "info" },
  1176: { name: "VGT Actuator Position (Cmd)", description: "Commanded VGT actuator vane position", fix: "Compare to actual position for diagnostic", severity: "info" },
  1177: { name: "VGT Actuator Position (Actual)", description: "Actual VGT actuator position", fix: "If stuck: replace VGT actuator, clean vane ring, check for soot binding", severity: "warning" },
  1180: { name: "Turbo Speed", description: "Turbocharger shaft rotational speed", fix: "Overspeed: check VGT/wastegate. Underspeed: check boost leak, bearing wear", severity: "warning" },
  1209: { name: "Exhaust Back Pressure", description: "Exhaust pressure upstream of aftertreatment", fix: "Check for plugged DPF, stuck VGT, exhaust brake valve", severity: "warning" },
  1243: { name: "Air Supply Pressure", description: "Primary brake system air supply pressure", fix: "Check air compressor, governor, air dryer", severity: "critical" },
  1431: { name: "Headlight Status", description: "Headlight circuit status", fix: "Check headlight switch, relays, bulbs, grounds", severity: "info" },
  1432: { name: "Turn Signal Status", description: "Turn signal activation status", fix: "Check multifunction switch, flasher module, bulbs", severity: "info" },
  1433: { name: "Marker/Clearance Lamps", description: "Marker and clearance lamp circuit", fix: "Check bulbs, fuses, switch, wiring", severity: "info" },
  1434: { name: "Backup Lamp Status", description: "Reverse/backup lamp circuit", fix: "Check reverse switch on transmission, bulbs, fuse", severity: "info" },
  1435: { name: "Stop Lamp Status", description: "Brake/stop lamp circuit", fix: "Check brake light switch, bulbs, fuse — DOT critical", severity: "warning" },
  1438: { name: "ESC Active", description: "Electronic Stability Control intervening", fix: "If frequent: check wheel speed sensors, steering angle sensor, load", severity: "info" },
  1439: { name: "ESC Lamp Status", description: "ESC warning lamp on dashboard", fix: "Read stability codes — yaw rate, steering angle, wheel speed sensors", severity: "warning" },
  1480: { name: "Exhaust Brake Status", description: "Exhaust brake butterfly valve status", fix: "Check actuator, solenoid, butterfly for soot binding", severity: "info" },
  1481: { name: "I-Shift Clutch Position", description: "Automated clutch actuator position", fix: "Check clutch actuator, wear, hydraulic fluid level", severity: "warning" },
  1636: { name: "I-Shift Clutch Wear", description: "Automated clutch lining wear estimate", fix: "Monitor wear %, plan clutch replacement near limit", severity: "warning" },
  1706: { name: "DTC Lamp - Protect", description: "Engine protection (red stop) lamp", fix: "Critical — ECM detected condition that could damage engine", severity: "critical" },
  1807: { name: "Steering Angle Sensor", description: "Steering wheel angle position", fix: "Recalibrate after alignment, replace if fault persists", severity: "warning" },
  1814: { name: "Yaw Rate", description: "Vehicle rotation around vertical axis", fix: "Replace yaw rate sensor if erratic, check mounting", severity: "warning" },
  1815: { name: "Lateral Acceleration", description: "Side-to-side vehicle acceleration", fix: "Check accelerometer/IMU, ensure proper mounting", severity: "warning" },
  1816: { name: "Roll Stability Active", description: "Roll Stability Control intervening", fix: "If on flat road: check load height sensor, lateral accel", severity: "info" },
  1821: { name: "Suspension Ride Height - LF", description: "Left front ride height sensor", fix: "Check sensor, linkage, air spring, leveling valve", severity: "info" },
  1822: { name: "Suspension Ride Height - RF", description: "Right front ride height sensor", fix: "Check sensor and air spring, compare L vs R", severity: "info" },
  1823: { name: "Suspension Ride Height - LR", description: "Left rear ride height sensor", fix: "Check sensor, air bag, leveling valve, air supply", severity: "info" },
  1824: { name: "Suspension Ride Height - RR", description: "Right rear ride height sensor", fix: "If truck leaning, suspect air spring leak or sensor failure", severity: "info" },
  1856: { name: "Driver Seat Weight", description: "Seat occupancy detection for safety systems", fix: "Check occupancy sensor, may affect airbag deployment", severity: "info" },
  2000: { name: "DPF Warning Lamp", description: "DPF requesting driver action for regen", fix: "Drive at highway speed or initiate parked regen", severity: "warning" },
  2393: { name: "Cab Tilt Warning", description: "Cab not fully latched in lowered position", fix: "Verify cab latch engagement, check sensor/switch", severity: "warning" },
  2394: { name: "Seat Belt Status", description: "Driver seat belt buckle switch", fix: "Check buckle switch and wiring", severity: "info" },
  2609: { name: "A/C Compressor Status", description: "A/C compressor clutch engagement", fix: "Check clutch, relay, pressure switches, refrigerant charge", severity: "info" },
  2610: { name: "A/C High Side Pressure", description: "Refrigerant high/discharge side pressure", fix: "Check condenser airflow, fan, refrigerant charge", severity: "warning" },
  2611: { name: "A/C Low Side Pressure", description: "Refrigerant low/suction side pressure", fix: "Low = leak or restriction, High = compressor issue", severity: "warning" },
  2612: { name: "A/C Refrigerant Temp", description: "A/C system refrigerant temperature", fix: "Check for evaporator freeze-up, compressor cycling", severity: "info" },
  3028: { name: "Trans Oil Life", description: "Transmission oil remaining useful life", fix: "Service trans oil and filter, reset counter", severity: "info" },
  3038: { name: "OBD Readiness Status", description: "OBD emissions monitor readiness", fix: "Drive through OBD cycle to complete monitors", severity: "info" },
  3039: { name: "OBD Distance Since Clear", description: "Miles driven since DTC clear", fix: "Informational for emissions inspections", severity: "info" },
  3040: { name: "Brake Temp - Steer Axle", description: "Front axle brake temperature", fix: "High temps = dragging brake, seized caliper", severity: "warning" },
  3041: { name: "Time Since DTC Clear", description: "Engine run time since codes cleared", fix: "Informational for inspections", severity: "info" },
  3058: { name: "DEF Warning Lamp", description: "DEF system warning lamp", fix: "Refill DEF if low, diagnose DEF system if persists", severity: "warning" },
  3249: { name: "DPF Soot Load", description: "DPF soot accumulation level", fix: "Initiate regen, clean or replace DPF if soot won't burn", severity: "warning" },
  3250: { name: "DPF Ash Load", description: "DPF ash accumulation (non-combustible)", fix: "DPF needs professional ash cleaning (bake and blow)", severity: "warning" },
  3291: { name: "Bunk Heater Status", description: "Auxiliary sleeper heater status", fix: "Check fuel supply, glow plug, combustion air blower", severity: "info" },
  3292: { name: "Bunk Heater Fault", description: "Sleeper heater fault detected", fix: "Read heater-specific codes, common: glow plug, fuel pump", severity: "warning" },
  3349: { name: "Trans Malfunction Indicator", description: "General transmission malfunction lamp", fix: "Read trans codes with OEM tool", severity: "warning" },
  3350: { name: "Trans Oil Pressure", description: "Transmission hydraulic oil pressure", fix: "Check trans oil level, filter, pump", severity: "warning" },
  3360: { name: "DEF Dosing Disabled", description: "DEF dosing disabled due to fault", fix: "Diagnose SCR inlet temp, exhaust sensors, DEF pump, injector", severity: "warning" },
  3361: { name: "DEF Dosing Valve", description: "DEF dosing injector fault", fix: "Inspect for crystallization, clean or replace, check coolant supply", severity: "warning" },
  3363: { name: "DEF Dosing Rate (Cmd)", description: "Commanded DEF injection rate", fix: "If commanding zero with high NOx, check SCR temp and faults", severity: "info" },
  3464: { name: "ECU Supply Voltage Low", description: "ECU power below minimum threshold", fix: "Check batteries, alternator, main relay, wiring, ground connections", severity: "critical" },
  3479: { name: "EGR Mass Flow (Actual)", description: "Actual exhaust gas flow through EGR", fix: "Compare to commanded, check EGR valve and diff pressure sensor", severity: "warning" },
  3480: { name: "AT Inlet NOx Sensor", description: "NOx at aftertreatment inlet (upstream SCR)", fix: "Replace inlet NOx sensor, check for exhaust leaks near sensor", severity: "warning" },
  3481: { name: "NOx Sensor - Inlet HW", description: "Inlet NOx sensor hardware fault", fix: "Replace inlet NOx sensor, check wiring and connector", severity: "warning" },
  3482: { name: "NOx Sensor - Outlet HW", description: "Outlet NOx sensor hardware fault", fix: "Replace outlet NOx sensor, common failure on Mack/Volvo", severity: "warning" },
  3509: { name: "CAN Message Counter Error", description: "CAN message sequence/checksum failed", fix: "Check CAN wiring for chafe, loose connectors, EMI", severity: "warning" },
  3521: { name: "DEF Pump Pressure", description: "DEF supply/dosing pump pressure", fix: "Check DEF pump, supply line, filter, replace pump module", severity: "warning" },
  3695: { name: "OBD Inducement Derate", description: "Emissions compliance derate active", fix: "Diagnose and repair emissions fault, reset timers with OEM tool", severity: "critical" },
  3697: { name: "DOC Conversion Efficiency", description: "Diesel Oxidation Catalyst efficiency", fix: "DOC may be degraded or poisoned, inspect and replace", severity: "warning" },
  3700: { name: "DPF Regen Frequency", description: "How often DPF regen events occur", fix: "Too frequent = excessive soot from short trips, EGR, or injector issues", severity: "warning" },
  3937: { name: "AT Inlet NOx Sensor Heater", description: "Inlet NOx sensor heater circuit", fix: "Replace inlet NOx sensor, verify power and ground", severity: "warning" },
  4331: { name: "DEF Pump Module", description: "General DEF supply pump module fault", fix: "Diagnose pump module: filter, lines, connector, replace if failed", severity: "warning" },
  4334: { name: "DEF System General Fault", description: "General DEF dosing/supply system fault", fix: "Full DEF system diagnostics: pump, filter, lines, injector, tank header", severity: "warning" },
  4342: { name: "DEF Line Pressure Deviation", description: "DEF pressure deviates from commanded", fix: "Check lines for crystallization/air, filter, pump, injector blockage", severity: "warning" },
  4360: { name: "DEF Tank Empty/Low", description: "DEF critically low, derate sequence started", fix: "Refill DEF immediately, vehicle will derate to 5mph if empty", severity: "critical" },
  4363: { name: "DEF Quality Non-Compliant", description: "DEF does not meet 32.5% urea spec", fix: "Drain and refill with certified DEF, flush lines, replace quality sensor", severity: "critical" },
  4365: { name: "AT Severe Derate - 5 MPH", description: "Vehicle speed limited to 5 MPH", fix: "Immediate repair required, diagnose SCR/NOx/DEF system failure", severity: "critical" },
  4766: { name: "AT HC Dosing Valve (7th Injector)", description: "Hydrocarbon doser for DPF regen", fix: "Inspect/replace 7th injector, check for coking, fuel supply", severity: "warning" },
  5394: { name: "SCR Conversion Efficiency", description: "NOx reduction efficiency of SCR catalyst", fix: "Check DEF dosing/quality, SCR temp, catalyst condition", severity: "warning" },
  5397: { name: "SCR Catalyst Temp", description: "SCR catalyst bed temperature", fix: "If too low: check exhaust leaks, DPF. If too high: check runaway regen", severity: "warning" },
  5571: { name: "DEF Dosing Line Heater", description: "DEF supply line heater circuit", fix: "Test heater resistance, check relay, wiring — common cold weather failure", severity: "warning" },
  5572: { name: "DEF Tank Heater", description: "DEF tank heating system fault", fix: "Check coolant flow to heater, valve, hoses, or electric heater element", severity: "warning" },
};

export function lookupSPN(spn: number): SPNInfo {
  return SPN_LOOKUP[spn] || {
    name: `SPN ${spn}`,
    description: "Unknown parameter — check J1939 SPN database",
    fix: "Consult service manual for this specific code",
    severity: "warning" as const,
  };
}

export function lookupFMI(fmi: number): string {
  return FMI_DESCRIPTIONS[fmi] || `Unknown failure mode ${fmi}`;
}
