/**
 * Generate an AI health summary for the diagnostic report.
 * Receives live readings + historical data, returns a concise narrative
 * that references actual measurements and trends as evidence.
 *
 * POST /api/ai-report-summary
 * Body: { readings: {...}, history: {...} }
 */

import { NextResponse } from "next/server";
import { requireRole } from "@/lib/auth-guard";

export async function POST(request: Request) {
  const denied = await requireRole("/api/ai-report-summary");
  if (denied) return denied;

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ summary: "" });
  }

  const body = await request.json();
  const { readings, history } = body;

  // Don't generate a summary if there's no real data
  const hasLiveData = readings && Object.keys(readings).some(k =>
    ["engine_rpm", "coolant_temp_f", "vehicle_speed_mph"].includes(k) && typeof readings[k] === "number"
  );
  const hasHistory = history && history.totalPoints > 0;

  if (!hasLiveData && !hasHistory) {
    return NextResponse.json({ summary: "" });
  }

  const readingsText = JSON.stringify(readings || {}, null, 2);
  const historyText = history && history.totalPoints > 0
    ? `HISTORICAL DATA (${history.totalMinutes} minutes, ${history.totalPoints} readings):\n${JSON.stringify(history.summary, null, 2)}\nDTC events: ${history.dtcEvents?.map((e: { code: string; timestamp: string }) => `${e.code} at ${e.timestamp}`).join(", ") || "none"}`
    : "No historical data available.";

  const prompt = `You are writing a vehicle health summary for a professional diagnostic report generated by IronSight Fleet Diagnostics. This will be printed and handed to a mechanic, fleet manager, or vehicle owner.

Write 2-3 short paragraphs summarizing the vehicle's current condition. You MUST reference specific numbers from the data as evidence for every claim you make. Do not make vague statements — tie every observation to a measurement.

Rules:
- CRITICAL: ONLY reference values that are ACTUALLY present in the data below. If a field is missing, empty, 0, or not present, do NOT mention it and do NOT make up values. If there is insufficient data to write a meaningful summary, say "Insufficient data for analysis" and nothing else.
- Be direct and factual. This is a report, not a conversation.
- Reference actual values: "Coolant temperature held steady at 186.8-188.6°F over 42 minutes, indicating a properly functioning thermostat."
- If trouble codes are present, explain what they mean in plain English and what the data suggests about the root cause.
- If fuel trims are outside ±10%, explain what that means.
- Note anything that looks concerning AND anything that looks healthy.
- Do NOT make safety judgments ("safe to drive" / "unsafe"). That is the mechanic's call.
- Do NOT use markdown headers (##). Use plain paragraphs only.
- Keep it under 200 words. This is a summary, not a full diagnosis.
- End with one sentence about what should be checked next.

CURRENT LIVE READINGS:
${readingsText}

${historyText}`;

  const startTime = Date.now();

  try {
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-20250514",
        max_tokens: 500,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!response.ok) {
      console.error("[API-ERROR]", "/api/ai-report-summary", `Claude API ${response.status}:`, await response.text());
      return NextResponse.json({ summary: "" });
    }

    const result = await response.json();
    const summary = result.content?.[0]?.text || "";

    // Log for analysis
    console.log("[AI-REPORT-SUMMARY]", JSON.stringify({
      type: "report_summary",
      timestamp: new Date().toISOString(),
      has_history: history?.totalPoints > 0,
      history_points: history?.totalPoints || 0,
      dtc_count: readings?.active_dtc_count || 0,
    }));

    console.log("[API-TIMING]", "/api/ai-report-summary", Date.now() - startTime, "ms");
    return NextResponse.json({ success: true, summary });
  } catch (err) {
    console.error("[API-ERROR]", "/api/ai-report-summary", err);
    return NextResponse.json({ summary: "" });
  }
}
