// Typed interfaces for sensor readings from PLC and J1939 modules.
// Copied from web dashboard: dashboard/lib/sensor-types.ts
// PRIVACY CONSTRAINT: No operator/personnel identification fields.

// PLC Sensor Readings (plc_sensor.py get_readings)
export interface PlcSensorReadings {
  truck_id?: string;
  session_id?: string;
  connected?: boolean;
  fault?: boolean;
  system_state?: string;
  last_fault?: string;
  uptime_seconds?: number;
  shift_hours?: number;
  total_reads?: number;
  total_errors?: number;
  ds1?: number;
  ds2?: number;
  ds3?: number;
  ds4?: number;
  ds5?: number;
  ds6?: number;
  ds7?: number;
  ds8?: number;
  ds9?: number;
  ds10?: number;
  ds11?: number;
  ds12?: number;
  ds13?: number;
  ds14?: number;
  ds15?: number;
  ds16?: number;
  ds17?: number;
  ds18?: number;
  ds19?: number;
  ds20?: number;
  ds21?: number;
  ds22?: number;
  ds23?: number;
  ds24?: number;
  ds25?: number;
  encoder_count?: number;
  dd1_frozen?: boolean;
  ds10_frozen?: boolean;
  encoder_direction?: "forward" | "reverse";
  encoder_distance_ft?: number;
  encoder_speed_ftpm?: number;
  encoder_revolutions?: number;
  encoder_enabled?: boolean;
  encoder_reset?: boolean;
  floating_zero?: boolean;
  tps_power_loop?: boolean;
  camera_signal?: boolean;
  x1?: boolean;
  x2?: boolean;
  x8?: boolean;
  eject_tps_1?: boolean;
  eject_left_tps_2?: boolean;
  eject_right_tps_2?: boolean;
  air_eagle_1_feedback?: boolean;
  air_eagle_2_feedback?: boolean;
  air_eagle_3_enable?: boolean;
  operating_mode?: string;
  mode_tps1_single?: boolean;
  mode_tps1_double?: boolean;
  mode_tps2_both?: boolean;
  mode_tps2_left?: boolean;
  mode_tps2_right?: boolean;
  mode_tie_team?: boolean;
  mode_2nd_pass?: boolean;
  drop_enable?: boolean;
  drop_enable_latch?: boolean;
  drop_software_eject?: boolean;
  drop_detector_eject?: boolean;
  drop_encoder_eject?: boolean;
  first_tie_detected?: boolean;
  encoder_mode?: boolean;
  camera_positive?: boolean;
  backup_alarm?: boolean;
  lay_ties_set?: boolean;
  drop_ties?: boolean;
  td5_seconds_laying?: number;
  td6_tie_travel?: number;
  plate_drop_count?: number;
  last_drop_spacing_in?: number;
  avg_drop_spacing_in?: number;
  min_drop_spacing_in?: number;
  max_drop_spacing_in?: number;
  distance_since_last_drop_in?: number;
  drop_count_in_window?: number;
  camera_detections_per_min?: number;
  camera_rate_trend?: "stable" | "declining" | "dead" | "intermittent";
  camera_signal_duration_s?: number;
  eject_rate_per_min?: number;
  detector_eject_rate_per_min?: number;
  encoder_noise?: number;
  encoder_reversals_per_min?: number;
  modbus_response_time_ms?: number;
  tps_power_duration_s?: number;
  eth0_status?: string;
  eth0_diagnosis?: string;
  eth0_error_rate?: number;
  eth0_link_speed_mbps?: number;
  eth0_link_uptime_seconds?: number;
  eth0_crc_errors?: number;
  eth0_link_flaps?: number;
  location_city?: string;
  location_region?: string;
  location_timezone?: string;
  weather?: string;
  weather_temp?: string;
  weather_humidity?: string;
  weather_wind?: string;
  local_time?: string;
  diagnostics?: DiagnosticResult[];
  diagnostics_count?: number;
  diagnostics_critical?: number;
  diagnostics_warning?: number;
  diagnostic_log?: string;
  diag_metrics?: string;
  chat_events?: unknown[];
  chat_event_count?: number;
  cpu_temp_c?: number | null;
  cpu_usage_pct?: number | null;
  load_1m?: number | null;
  load_5m?: number | null;
  memory_total_mb?: number | null;
  memory_used_mb?: number | null;
  memory_used_pct?: number | null;
  disk_used_pct?: number | null;
  disk_free_gb?: number | null;
  wifi_ssid?: string | null;
  wifi_signal_pct?: number | null;
  wifi_signal_dbm?: number | null;
  tailscale_ip?: string | null;
  tailscale_online?: boolean;
  internet?: boolean;
  sync_pending_files?: number | null;
  sync_pending_mb?: number | null;
  sync_oldest_age_min?: number | null;
  sync_failed_files?: number | null;
  sync_ok?: boolean | null;
}

export interface TruckSensorReadings {
  engine_rpm?: number;
  engine_load_pct?: number;
  accel_pedal_pos_pct?: number;
  driver_demand_torque_pct?: number;
  actual_engine_torque_pct?: number;
  engine_hours?: number;
  coolant_temp_f?: number;
  oil_temp_f?: number;
  fuel_temp_f?: number;
  intake_manifold_temp_f?: number;
  trans_oil_temp_f?: number;
  ambient_temp_f?: number;
  hydraulic_oil_temp_f?: number;
  oil_pressure_psi?: number;
  fuel_pressure_psi?: number;
  boost_pressure_psi?: number;
  barometric_pressure_psi?: number;
  exhaust_gas_pressure_psi?: number;
  hydraulic_oil_pressure_psi?: number;
  oil_level_pct?: number;
  fuel_level_pct?: number;
  fuel_rate_gph?: number;
  fuel_economy_mpg?: number;
  total_fuel_used_gal?: number;
  idle_fuel_used_gal?: number;
  trip_fuel_gal?: number;
  trip_fuel_2_gal?: number;
  vehicle_speed_mph?: number;
  current_gear?: number;
  selected_gear?: number;
  trans_output_rpm?: number;
  clutch_slip_pct?: number;
  cruise_control_active?: number;
  front_axle_speed_mph?: number;
  battery_voltage_v?: number;
  vehicle_distance_mi?: number;
  vehicle_distance_hr_mi?: number;
  service_distance_mi?: number;
  idle_engine_hours?: number;
  pto_engaged?: number;
  pto_rpm?: number;
  pto_set_rpm?: number;
  pto_switches?: number;
  hydraulic_oil_level_pct?: number;
  retarder_torque_pct?: number;
  retarder_torque_mode?: number;
  brake_pedal_pos_pct?: number;
  abs_active?: number;
  brake_air_pressure_psi?: number;
  air_supply_pressure_psi?: number;
  air_pressure_circuit1_psi?: number;
  air_pressure_circuit2_psi?: number;
  scr_efficiency_pct?: number;
  def_level_pct?: number;
  def_temp_f?: number;
  def_dose_rate_gs?: number;
  def_dose_commanded_gs?: number;
  def_dosing_active?: boolean;
  def_low?: boolean;
  dpf_soot_load_pct?: number;
  dpf_regen_status?: number;
  dpf_regen_inhibit?: number;
  dpf_diff_pressure_psi?: number;
  dpf_inlet_temp_f?: number;
  dpf_outlet_temp_f?: number;
  nox_inlet_ppm?: number;
  nox_outlet_ppm?: number;
  nox_inlet_power_ok?: number;
  nox_inlet_at_temp?: number;
  nox_inlet_reading_stable?: number;
  nox_outlet_power_ok?: number;
  nox_outlet_at_temp?: number;
  nox_outlet_reading_stable?: number;
  scr_catalyst_temp_f?: number;
  dpf_health?: "OK" | "WARNING" | "CRITICAL";
  scr_health?: "OK" | "WARNING" | "CRITICAL";
  battery_health?: "OK" | "LOW" | "CRITICAL" | "OVERCHARGE";
  gps_latitude?: number;
  gps_longitude?: number;
  compass_bearing_deg?: number;
  altitude_ft?: number;
  nav_speed_mph?: number;
  vehicle_pitch_deg?: number;
  protect_lamp?: number;
  amber_warning_lamp?: number;
  red_stop_lamp?: number;
  malfunction_lamp?: number;
  mil_engine?: number;
  amber_lamp_engine?: number;
  red_stop_lamp_engine?: number;
  protect_lamp_engine?: number;
  mil_acm?: number;
  amber_lamp_acm?: number;
  red_stop_lamp_acm?: number;
  protect_lamp_acm?: number;
  mil_trans?: number;
  amber_lamp_trans?: number;
  red_stop_lamp_trans?: number;
  protect_lamp_trans?: number;
  mil_abs?: number;
  amber_lamp_abs?: number;
  red_stop_lamp_abs?: number;
  protect_lamp_abs?: number;
  active_dtc_count?: number;
  dtc_engine_count?: number;
  dtc_trans_count?: number;
  dtc_abs_count?: number;
  dtc_acm_count?: number;
  dtc_body_count?: number;
  dtc_inst_count?: number;
  [key: `dtc_${string}_${number}_${"spn" | "fmi" | "occurrence"}`]: number | undefined;
  dtc_0_spn?: number;
  dtc_0_fmi?: number;
  dtc_0_occurrence?: number;
  dtc_1_spn?: number;
  dtc_1_fmi?: number;
  dtc_1_occurrence?: number;
  prev_dtc_count?: number;
  fan_speed_pct?: number;
  turbo_wastegate_pct?: number;
  vehicle_state?: "Truck Off" | "Engine On" | "Ignition On" | "Unknown";
  idle_waste_active?: boolean;
  harsh_braking?: boolean;
  harsh_acceleration?: boolean;
  harsh_behavior_flag?: boolean;
  fuel_cost_per_hour?: number;
  fuel_cost_per_mile?: number;
  idle_waste_dollars?: number;
  idle_pct?: number;
  idle_fuel_pct?: number;
  pto_active?: boolean;
  vehicle_vin?: string;
  vehicle_protocol?: "j1939" | "obd2";
  vehicle_make?: string;
  vehicle_model?: string;
  vehicle_year?: number;
  _protocol?: "j1939" | "obd2";
  _can_interface?: string;
  _frame_count?: number;
  _bus_connected?: boolean;
  _seconds_since_last_frame?: number;
  _vehicle_off?: boolean;
  can_bitrate?: number;
  cpu_temp_c?: number | null;
  cpu_usage_pct?: number | null;
  load_1m?: number | null;
  memory_total_mb?: number | null;
  memory_used_mb?: number | null;
  memory_used_pct?: number | null;
  disk_used_pct?: number | null;
  disk_free_gb?: number | null;
  wifi_ssid?: string | null;
  wifi_signal_pct?: number | null;
  tailscale_ip?: string | null;
  tailscale_online?: boolean;
  internet?: boolean;
  uptime_seconds?: number | null;
  sync_pending_files?: number | null;
  sync_pending_mb?: number | null;
  sync_oldest_age_min?: number | null;
  sync_failed_files?: number | null;
  sync_ok?: boolean | null;
}

export type DiagnosticSeverity = "critical" | "warning" | "info";
export type DiagnosticCategory = "camera" | "encoder" | "eject" | "plc" | "operation";

export interface DiagnosticResult {
  rule: string;
  severity: DiagnosticSeverity;
  category: DiagnosticCategory;
  title: string;
  action: string;
  evidence: string;
}

export interface GaugeThreshold {
  warn: number;
  crit: number;
  inverted?: boolean;
}

export type GaugeThresholds = Record<string, GaugeThreshold>;
